import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { VehicleRecord, MonthKey, InsuranceCompany } from '../types';

interface PDFExportOptions {
  records: VehicleRecord[];
  monthTitle: string;
  year: number;
  generatedBy?: string;
  insuranceFilter?: string;
}

export const generateVehicleLedgerPDF = ({
  records,
  monthTitle,
  year,
  generatedBy = 'Htay Aung',
  insuranceFilter = 'All',
}: PDFExportOptions) => {
  // Create PDF in landscape orientation for clean multi-column table presentation
  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'pt',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // Metrics calculation
  const totalVehicles = records.length;
  const totalCarValue = records.reduce((acc, r) => acc + (r.carValue || 0), 0);
  const totalWindshield = records.reduce((acc, r) => acc + (r.windshieldValue || 0), 0);
  const totalPremium = records.reduce((acc, r) => acc + (r.premiumAmount || 0), 0);

  // Breakdown by insurance company
  const companies: InsuranceCompany[] = ['Young', 'GGI', 'FNI', 'KBZ', 'MI'];
  const companyCounts = companies.map(c => {
    const list = records.filter(r => r.insuranceCompany === c);
    const prem = list.reduce((acc, r) => acc + (r.premiumAmount || 0), 0);
    return { name: c, count: list.length, premium: prem };
  });

  // Header Banner
  doc.setFillColor(30, 58, 138); // Deep Navy / Royal Blue
  doc.rect(0, 0, pageWidth, 56, 'F');

  // Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(255, 255, 255);
  doc.text('AutoLedger · Vehicle Rental & Insurance Ledger Report', 36, 34);

  // Subtitle / Month Badge
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(224, 231, 255);
  doc.text(`Report Period: ${monthTitle} ${year} | Filter: ${insuranceFilter}`, pageWidth - 36, 26, { align: 'right' });
  doc.text(`Generated by: ${generatedBy} | Date: ${new Date().toLocaleDateString()}`, pageWidth - 36, 42, { align: 'right' });

  // Summary Metrics Section (Cards at top)
  const startY = 70;
  const cardWidth = (pageWidth - 72 - 36) / 4;
  const cardHeight = 44;

  const summaryItems = [
    { label: 'TOTAL VEHICLES', value: `${totalVehicles} units`, color: [241, 245, 249], textColor: [15, 23, 42] },
    { label: 'TOTAL CAR VALUE', value: `${totalCarValue.toLocaleString()} MMK`, color: [238, 242, 255], textColor: [49, 46, 129] },
    { label: 'WINDSHIELD COVERAGE', value: `${totalWindshield.toLocaleString()} MMK`, color: [240, 253, 250], textColor: [19, 78, 74] },
    { label: 'PREMIUM COLLECTED', value: `${totalPremium.toLocaleString()} MMK`, color: [236, 253, 245], textColor: [6, 95, 70] },
  ];

  summaryItems.forEach((item, idx) => {
    const x = 36 + idx * (cardWidth + 12);
    doc.setFillColor(item.color[0], item.color[1], item.color[2]);
    doc.roundedRect(x, startY, cardWidth, cardHeight, 4, 4, 'F');
    doc.setDrawColor(226, 232, 240);
    doc.roundedRect(x, startY, cardWidth, cardHeight, 4, 4, 'S');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7.5);
    doc.setTextColor(100, 116, 139);
    doc.text(item.label, x + 10, startY + 16);

    doc.setFontSize(11);
    doc.setTextColor(item.textColor[0], item.textColor[1], item.textColor[2]);
    doc.text(item.value, x + 10, startY + 34);
  });

  // Insurance Breakdown Bar
  const breakdownY = startY + cardHeight + 10;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(71, 85, 105);
  const compSummaryText = companyCounts
    .map(c => `${c.name}: ${c.count} vehicles (${c.premium.toLocaleString()} MMK)`)
    .join('   |   ');
  doc.text(`Insurance Breakdown:  ${compSummaryText}`, 36, breakdownY);

  // Table Data Preparation
  const tableHeaders = [
    'No.',
    'Vehicle No',
    'Insurance Co',
    'Owner / Customer',
    'Car Value (MMK)',
    'Windshield (MMK)',
    'Premium (MMK)',
    'Status',
    'Validity Period',
    'Claim Dt',
    'Comm Dt',
    'Invoice #',
    'Remarks'
  ];

  const tableRows = records.map((r, i) => [
    r.srNo || i + 1,
    r.vehicleNo || '—',
    r.insuranceCompany || 'Young',
    r.ownerName || '—',
    (r.carValue || 0).toLocaleString(),
    (r.windshieldValue || 0).toLocaleString(),
    (r.premiumAmount || 0).toLocaleString(),
    r.status || 'Rental',
    r.validityPeriod || '—',
    r.claimDate || 'None',
    r.commissionDate || '—',
    r.invoiceNo || '—',
    r.remarks || '—'
  ]);

  // If no records exist, add empty placeholder row
  if (tableRows.length === 0) {
    tableRows.push(['—', 'No records found for this period', '—', '—', '0', '0', '0', '—', '—', '—', '—', '—', '—']);
  }

  // Generate Table using autoTable
  autoTable(doc, {
    startY: breakdownY + 8,
    head: [tableHeaders],
    body: tableRows,
    theme: 'grid',
    headStyles: {
      fillColor: [30, 41, 59], // Slate 800
      textColor: [255, 255, 255],
      fontSize: 8,
      fontStyle: 'bold',
      halign: 'left',
      cellPadding: 4,
    },
    bodyStyles: {
      fontSize: 7.5,
      textColor: [30, 41, 59],
      cellPadding: 3.5,
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
    columnStyles: {
      0: { cellWidth: 26, halign: 'center' }, // No
      1: { cellWidth: 70, fontStyle: 'bold' }, // Vehicle No
      2: { cellWidth: 55 }, // Insurance Co
      3: { cellWidth: 85 }, // Owner
      4: { cellWidth: 55, halign: 'right' }, // Car Value
      5: { cellWidth: 55, halign: 'right' }, // Windshield
      6: { cellWidth: 55, halign: 'right', fontStyle: 'bold' }, // Premium
      7: { cellWidth: 50 }, // Status
      8: { cellWidth: 75 }, // Validity
      9: { cellWidth: 50 }, // Claim Dt
      10: { cellWidth: 50 }, // Comm Dt
      11: { cellWidth: 55 }, // Invoice #
      12: { cellWidth: 'auto' }, // Remarks
    },
    foot: [
      [
        'Total',
        `${totalVehicles} records`,
        '',
        '',
        `${totalCarValue.toLocaleString()} MMK`,
        `${totalWindshield.toLocaleString()} MMK`,
        `${totalPremium.toLocaleString()} MMK`,
        '',
        '',
        '',
        '',
        '',
        ''
      ]
    ],
    footStyles: {
      fillColor: [241, 245, 249],
      textColor: [15, 23, 42],
      fontSize: 8,
      fontStyle: 'bold',
      cellPadding: 4,
    },
    margin: { left: 36, right: 36, bottom: 36 },
    didDrawPage: (data) => {
      // Footer page numbering
      const str = `Page ${doc.internal.pages.length - 1}`;
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);
      doc.text(
        `AutoLedger Fleet System · Confidential Report · Authorized: ${generatedBy}`,
        36,
        pageHeight - 16
      );
      doc.text(str, pageWidth - 36, pageHeight - 16, { align: 'right' });
    }
  });

  // Save the PDF
  const filename = `AutoLedger_Report_${monthTitle}_${year}.pdf`.replace(/\s+/g, '_');
  doc.save(filename);
};
